### ISSUE TITLE
add copyright text

### ISSUE THREAD

**Issue by karmelalla** [allaiphoto/allaiphoto.com#3]
@karmelalla provide text in comment

**Comment by karmelalla** [comment]
< ?php $the_year = date("Y"); echo $the_year; ? >
< ?php bloginfo('url'); ? >
All Rights Reserved.


© Alla Isakova and AllaIphoto, [Current Year or Year Range]. Unauthorized use and/or duplication of this material without express and written permission from this blog’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to Alla Isakova and AllaIPhoto with appropriate and specific direction to the original content.

**Comment by karmelalla** [comment]
© Alla Isakova and AllaIphoto, [Current Year or Year Range]. Unauthorized use and/or duplication of this material without express and written permission from this blog’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to Alla Isakova and AllaIPhoto with appropriate and specific direction to the original content.

**Comment by kisakov** [comment]
Available only on albums page because it's too big. 

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/586958/110230650-508de400-7ec7-11eb-8336-e9938f416543.png">
